model_list:
  - model_name: meta-llama/Meta-Llama-3-8B-Instruct
    litellm_params:
      model: meta-llama/Meta-Llama-3-8B-Instruct
      api_base: http://vllm:8000/v1
      api_key: "a"
      custom_llm_provider: openai
